apps/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('mesas_estado/', views.MesaEstadoListView.as_view(), name='mesas_estado_list'),
    path('mesas_estado/nuevo/', views.MesaEstadoCreateView.as_view(), name='mesas_estado_create'),
    path('mesas_estado/editar/<int:pk>/', views.MesaEstadoUpdateView.as_view(), name='mesas_estado_update'),
    path('mesas_estado/eliminar/<int:pk>/', views.MesaEstadoDeleteView.as_view(), name='mesas_estado_delete'),
    path('mesas/', views.MesaListView.as_view(), name='mesas_list'),
    path('mesas/nuevo/', views.MesaCreateView.as_view(), name='mesas_create'),
    path('mesas/editar/<int:pk>/', views.MesaUpdateView.as_view(), name='mesas_update'),
    path('mesas/eliminar/<int:pk>/', views.MesaDeleteView.as_view(), name='mesas_delete'),
    path('ordenes/', views.OrdenListView.as_view(), name='ordenes_list'),
    path('ordenes/nuevo/', views.OrdenCreateView.as_view(), name='ordenes_create'),
    path('ordenes/<int:orden_id>/detalles/', views.OrdenDetalleView.as_view(), name='ordenes_detalle_list'),
    path('ordenes/<int:pk>/detalles/edit/', views.OrdenDetalleUpdateView.as_view(), name='ordenes_detalle_update'),
    path('ordenes/detalles/eliminar/<int:pk>/', views.OrdenDetalleDeleteView.as_view(), name='ordenes_detalle_delete'),
    path('ordenes/<int:orden_id>/pagar', views.OrdenPagarView.as_view(), name='ordenes_pagar'),
    path('metodos_pago/', views.MetodoPagoListView.as_view(), name='metodos_pago_list'),
    path('metodos_pago/nuevo/', views.MetodoPagoCreateView.as_view(), name='metodos_pago_create'),
    path('metodos_pago/editar/<int:pk>/', views.MetodoPagoUpdateView.as_view(), name='metodos_pago_edit'),
    path('metodos_pago/eliminar/<int:pk>/', views.MetodoPagoDeleteView.as_view(), name='metodos_pago_delete'),
    path('pagos/', views.PagoListView.as_view(), name='pagos_list'),
]

restaurante_marisco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_index, name='main_index'),
    path('accounts/', include('apps.accounts.urls')),
    path('platillos/', include('apps.platillos.urls')),
    path('ordenes/', include('apps.ordenes.urls')),
    path('dashboard/', views.index_user, name='index_user'),
    path('api/', include('apps.api.urls')),
]

templates/mesas/mesas_confirm_delete.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Eliminar mesa</h1>

<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar el estado de mesas: "{{ object.nombre }}"?</p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a class="btn btn-primary" href="{% url 'ordenes:mesas_list' %}">Regresar</a>
</form>
{% endblock %}

templates/mesas/mesas_edit_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Editar mesa</h1>

<form action="{% url 'ordenes:mesas_update' form.instance.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/mesas/mesas_estado_confirm_delete.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Eliminar mesa estado</h1>

<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar el estado de mesas: "{{ object.nombre }}"?</p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a class="btn btn-primary" href="{% url 'ordenes:mesas_estado_list' %}">Regresar</a>
</form>
{% endblock %}

templates/mesas/mesas_estado_edit_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Editar estado de mesas</h1>

<form action="{% url 'ordenes:mesas_estado_update' form.instance.pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/mesas/mesas_estado_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar estado de mesas</h1>

<form action="{% url 'ordenes:mesas_estado_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/mesas/mesas_estado_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de estados de mesas</h1>

<a class="btn btn-primary" href="{% url 'ordenes:mesas_estado_create' %}">Agregar estado de mesa</a>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Nombre</th>
        </tr>
    </thead>
    <tbody>
        {% for mesa_estado in mesas_estados %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'ordenes:mesas_estado_update' mesa_estado.pk %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'ordenes:mesas_estado_delete' mesa_estado.pk %}">Eliminar</a>
            </td>
            <td>{{ mesa_estado.nombre }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/mesas/mesas_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar mesa</h1>

<form action="{% url 'ordenes:mesas_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/mesas/mesas_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de mesas</h1>

<a class="btn btn-primary" href="{% url 'ordenes:mesas_create' %}">Agregar mesa</a>
<a class="btn btn-primary" href="{% url 'ordenes:mesas_estado_list' %}">Estados de mesas</a>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Nombre</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        {% for mesa in mesas %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'ordenes:mesas_update' mesa.pk %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'ordenes:mesas_delete' mesa.pk %}">Eliminar</a>
            </td>
            <td>{{ mesa.nombre }}</td>
            <td>{{ mesa.estado.nombre }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}