apps/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('mesas_estado/', views.MesaEstadoListView.as_view(), name='mesas_estado_list'),
    path('mesas_estado/nuevo/', views.MesaEstadoCreateView.as_view(), name='mesas_estado_create'),
    path('mesas_estado/editar/<int:pk>/', views.MesaEstadoUpdateView.as_view(), name='mesas_estado_update'),
    path('mesas_estado/eliminar/<int:pk>/', views.MesaEstadoDeleteView.as_view(), name='mesas_estado_delete'),
    path('mesas/', views.MesaListView.as_view(), name='mesas_list'),
    path('mesas/nuevo/', views.MesaCreateView.as_view(), name='mesas_create'),
    path('mesas/editar/<int:pk>/', views.MesaUpdateView.as_view(), name='mesas_update'),
    path('mesas/eliminar/<int:pk>/', views.MesaDeleteView.as_view(), name='mesas_delete'),
    path('ordenes/', views.OrdenListView.as_view(), name='ordenes_list'),
    path('ordenes/nuevo/', views.OrdenCreateView.as_view(), name='ordenes_create'),
    path('ordenes/<int:orden_id>/detalles/', views.OrdenDetalleView.as_view(), name='ordenes_detalle_list'),
    path('ordenes/<int:pk>/detalles/edit/', views.OrdenDetalleUpdateView.as_view(), name='ordenes_detalle_update'),
    path('ordenes/detalles/eliminar/<int:pk>/', views.OrdenDetalleDeleteView.as_view(), name='ordenes_detalle_delete'),
    path('ordenes/<int:orden_id>/pagar', views.OrdenPagarView.as_view(), name='ordenes_pagar'),
    path('metodos_pago/', views.MetodoPagoListView.as_view(), name='metodos_pago_list'),
    path('metodos_pago/nuevo/', views.MetodoPagoCreateView.as_view(), name='metodos_pago_create'),
    path('metodos_pago/editar/<int:pk>/', views.MetodoPagoUpdateView.as_view(), name='metodos_pago_edit'),
    path('metodos_pago/eliminar/<int:pk>/', views.MetodoPagoDeleteView.as_view(), name='metodos_pago_delete'),
    path('pagos/', views.PagoListView.as_view(), name='pagos_list'),
]

restaurante_marisco/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_index, name='main_index'),
    path('accounts/', include('apps.accounts.urls')),
    path('platillos/', include('apps.platillos.urls')),
    path('ordenes/', include('apps.ordenes.urls')),
    path('dashboard/', views.index_user, name='index_user'),
    path('api/', include('apps.api.urls')),
]

apps/ordenes/models.py
from django.db import models
from apps.accounts.models import AppUser
from apps.platillos.models import Platillo

class MesaEstado(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Mesa(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    capacidad = models.IntegerField(null=False)
    estado = models.ForeignKey(MesaEstado, on_delete=models.CASCADE, related_name='mesas_estado')

    def __str__(self):
        return self.nombre

class Orden(models.Model):
    empleado = models.ForeignKey(AppUser, on_delete=models.CASCADE, related_name='ordenes')
    mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE, related_name='ordenes')
    fecha_hora = models.DateTimeField(auto_now_add=True)
    estatus = models.CharField(max_length=50, default='pendiente')

    @property
    def total(self):
        detalles = self.detalles.all()
        return sum(detalle.subtotal for detalle in detalles)

class OrdenDetalle(models.Model):
    orden = models.ForeignKey(Orden, on_delete=models.CASCADE, related_name='detalles')
    platillo = models.ForeignKey(Platillo, on_delete=models.CASCADE, related_name='detalles')
    cantidad = models.IntegerField()
    notas = models.TextField(blank=True, null=True)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.platillo.nombre} x {self.cantidad} (Orden #{self.orden.id})"

    @property
    def subtotal(self):
        return self.cantidad * self.precio_unitario

class MetodoPago(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Pago(models.Model):
    orden = models.ForeignKey(Orden, on_delete=models.CASCADE, related_name='pagos')
    metodo_pago = models.ForeignKey(MetodoPago, on_delete=models.CASCADE, related_name='pagos')
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_hora = models.DateTimeField(auto_now_add=True)
    

apps/ordenes/forms.py
import django.forms as forms
from .models import Mesa, MesaEstado, Orden, MetodoPago, Pago
from apps.platillos.models import Platillo

class MesaEstadoForm(forms.ModelForm):
    class Meta:
        model = MesaEstado
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'})
        }

class MesaForm(forms.ModelForm):
    class Meta:
        model = Mesa
        fields = ['nombre', 'capacidad', 'estado']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'capacidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'})
        }

class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['mesa', 'empleado']
        widgets = {
            'mesa': forms.Select(attrs={'class': 'form-control'}),
            'empleado': forms.HiddenInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'mesa' in self.fields:
            self.fields['mesa'].queryset = Mesa.objects.filter(estado__nombre__iexact='Disponible')

    def save(self, commit=True):
        orden = super().save(commit=False)
        if commit:
            orden.estatus = 'pendiente'  # Set default status
            orden.empleado = self.initial['empleado']
            orden.save()

            mesa = orden.mesa
            mesa.estado = MesaEstado.objects.get(nombre='Ocupada')
            mesa.save()
        return orden

class OrdenDetalleForm(forms.Form):
    platillo = forms.ModelChoiceField(queryset=Platillo.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))
    cantidad = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    notas = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}), required=False)    
    orden_id = forms.IntegerField(widget=forms.HiddenInput())

class MetodoPagoForm(forms.ModelForm):
    class Meta:
        model = MetodoPago
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'})
        }

class PagoForm(forms.ModelForm):
    class Meta:
        model = Pago
        fields = ['orden', 'metodo_pago', 'cantidad']
        widgets = {
            'orden': forms.HiddenInput(),
            'metodo_pago': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'})
        }

apps/ordenes/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import redirect
from .models import Mesa, MesaEstado, Orden, OrdenDetalle, MetodoPago, Pago
from .forms import MesaEstadoForm, MesaForm, OrdenForm, OrdenDetalleForm, MetodoPagoForm, PagoForm

class MesaEstadoListView(LoginRequiredMixin, ListView):
    model = MesaEstado
    template_name = 'mesas/mesas_estado_list.html'
    context_object_name = 'mesas_estados'

class MesaEstadoCreateView(LoginRequiredMixin, CreateView):
    model = MesaEstado
    form_class = MesaEstadoForm
    template_name = 'mesas/mesas_estado_form.html'
    success_url = '/ordenes/mesas_estado/'

class MesaEstadoUpdateView(LoginRequiredMixin, UpdateView):
    model = MesaEstado
    form_class = MesaEstadoForm
    template_name = 'mesas/mesas_estado_edit_form.html'
    success_url = '/ordenes/mesas_estado/'

class MesaEstadoDeleteView(LoginRequiredMixin, DeleteView):
    model = MesaEstado
    template_name = 'mesas/mesas_estado_confirm_delete.html'
    success_url = '/ordenes/mesas_estado/'

class MesaListView(LoginRequiredMixin, ListView):
    model = Mesa
    template_name = 'mesas/mesas_list.html'
    context_object_name = 'mesas'

class MesaCreateView(LoginRequiredMixin, CreateView):
    model = Mesa
    form_class = MesaForm
    template_name = 'mesas/mesas_form.html'
    success_url = '/ordenes/mesas/'

class MesaUpdateView(LoginRequiredMixin, UpdateView):
    model = Mesa
    form_class = MesaForm
    template_name = 'mesas/mesas_edit_form.html'
    success_url = '/ordenes/mesas/'

class MesaDeleteView(LoginRequiredMixin, DeleteView):
    model = Mesa
    template_name = 'mesas/mesas_confirm_delete.html'
    success_url = '/ordenes/mesas/'

class OrdenListView(LoginRequiredMixin, ListView):
    model = Orden
    template_name = 'ordenes/ordenes_list.html'
    context_object_name = 'ordenes'
    ordering = ['-fecha_hora']

class OrdenCreateView(LoginRequiredMixin, CreateView):
    model = Orden
    form_class = OrdenForm
    template_name = 'ordenes/ordenes_form.html'
    success_url = '/ordenes/ordenes/'

    def get_initial(self):
        initial = super().get_initial()
        initial['empleado'] = self.request.user
        return initial

class OrdenDetalleView(LoginRequiredMixin, ListView):
    model = OrdenDetalle
    template_name = 'ordenes/orden_detalle_list.html'
    context_object_name = 'orden_detalles'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orden'] = Orden.objects.get(id=self.kwargs.get('orden_id'))
        context['form'] = OrdenDetalleForm(initial={'orden_id': self.kwargs.get('orden_id')})
        return context

    def get_queryset(self):
        orden_id = self.kwargs.get('orden_id')
        return OrdenDetalle.objects.filter(orden__id=orden_id)
    
    def post(self, request, *args, **kwargs):
        form = OrdenDetalleForm(request.POST)
        if form.is_valid():
            orden_detalle = OrdenDetalle(
                orden=Orden.objects.get(id=form.cleaned_data['orden_id']),
                platillo=form.cleaned_data['platillo'],
                cantidad=form.cleaned_data['cantidad'],
                notas=form.cleaned_data['notas'],
                precio_unitario=form.cleaned_data['platillo'].precio
            )
            orden_detalle.save()
            return self.get(request, *args, **kwargs)
        else:
            return render(request, self.template_name, {'form': form, 'orden_detalles': self.get_queryset(), 'orden': Orden.objects.get(id=self.kwargs.get('orden_id'))})

class OrdenDetalleUpdateView(LoginRequiredMixin, View):
    def get(self, request, pk):
        detalle = OrdenDetalle.objects.get(id=pk)
        form = OrdenDetalleForm(initial={
            'platillo': detalle.platillo,
            'cantidad': detalle.cantidad,
            'notas': detalle.notas,
            'orden_id': detalle.orden.id
        })
        return render(request, 'ordenes/orden_detalle_edit_form.html', {'form': form, 'detalle': detalle})

    def post(self, request, pk):
        detalle = OrdenDetalle.objects.get(id=pk)
        form = OrdenDetalleForm(request.POST)
        if form.is_valid():
            detalle.platillo = form.cleaned_data['platillo']
            detalle.cantidad = form.cleaned_data['cantidad']
            detalle.notas = form.cleaned_data['notas']
            detalle.precio_unitario = form.cleaned_data['platillo'].precio
            detalle.save()
            return render(request, 'ordenes/orden_detalle_list.html', {
                'orden_detalles': OrdenDetalle.objects.filter(orden=detalle.orden),
                'orden': detalle.orden,
                'form': OrdenDetalleForm(initial={'orden_id': detalle.orden.id})
            })
        else:
            return render(request, 'ordenes/orden_detalle_edit_form.html', {'form': form, 'detalle': detalle})


class OrdenDetalleDeleteView(LoginRequiredMixin, DeleteView):
    model = OrdenDetalle
    template_name = 'ordenes/orden_detalle_confirm_delete.html'

    def get_success_url(self):
        return f'/ordenes/ordenes/{self.object.orden.id}/detalles/'

class OrdenPagarView(LoginRequiredMixin, View):
    def get(self, request, orden_id):
        orden = Orden.objects.get(id=orden_id)
        detalles = OrdenDetalle.objects.filter(orden=orden)
        total = sum(detalle.cantidad * detalle.precio_unitario for detalle in detalles)
        
        form = PagoForm(initial={'orden': orden, 'cantidad': total})

        return render(request, 'ordenes/ordenes_pagar.html', {'orden': orden, 'detalles': detalles, 'total': total, 'form': form})
    def post(self, request, orden_id):
        form = PagoForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                pago = form.save(commit=False)
                pago.orden = Orden.objects.get(id=orden_id)
                pago.save()

                orden = pago.orden
                orden.estatus = 'pagada'
                orden.save()

                mesa = orden.mesa
                mesa.estado = MesaEstado.objects.get(nombre='Disponible')
                mesa.save()

                return redirect('ordenes:ordenes_list')
        return render(request, 'ordenes/ordenes_pagar.html', {'form': form})

class MetodoPagoListView(LoginRequiredMixin, ListView):
    model = MetodoPago
    template_name = 'pagos/metodos_pago_list.html'
    context_object_name = 'metodos_pago'

class MetodoPagoCreateView(LoginRequiredMixin, CreateView):
    model = MetodoPago
    form_class = MetodoPagoForm
    template_name = 'pagos/metodos_pago_form.html'
    success_url = '/ordenes/metodos_pago/'

class MetodoPagoUpdateView(LoginRequiredMixin, UpdateView):
    model = MetodoPago
    form_class = MetodoPagoForm
    template_name = 'pagos/metodos_pago_edit_form.html'
    success_url = '/ordenes/metodos_pago/'

class MetodoPagoDeleteView(LoginRequiredMixin, DeleteView):
    model = MetodoPago
    template_name = 'pagos/metodos_pago_confirm_delete.html'
    success_url = '/ordenes/metodos_pago/'    

class PagoListView(LoginRequiredMixin, ListView):
    model = Pago
    template_name = 'pagos/pagos_list.html'
    context_object_name = 'pagos'

templates/ordenes/orden_detalle_confirm_delete.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Eliminar categoría</h1>

<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que deseas eliminar el platillo de orden: "{{ object.platillo }}"?</p>
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a class="btn btn-primary" href="{% url 'ordenes:ordenes_detalle_list' object.orden.id %}">Regresar</a>
</form>
{% endblock %}

templates/ordenes/orden_detalle_edit_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Editar Detalle de Orden</h1>

<form action="{% url 'ordenes:ordenes_detalle_update' detalle.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
    <a href="{% url 'ordenes:ordenes_detalle_list' detalle.orden.id %}" class="btn btn-secondary">Regresar</a>
</form>

{% endblock %}

templates/ordenes/orden_detalle_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Orden No. {{ orden.id }} - {{ orden.fecha_hora }}</h1>

<form action="{% url 'ordenes:ordenes_detalle_list' orden.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Platillo</th>
            <th>Cantidad</th>
            <th>Notas</th>            
        </tr>
    </thead>
    <tbody>
        {% for detalle in orden_detalles %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'ordenes:ordenes_detalle_update' detalle.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'ordenes:ordenes_detalle_delete' detalle.id %}">Eliminar</a>
            </td>
            <td>{{detalle.platillo.nombre}}</td>
            <td>{{detalle.cantidad}}</td>
            <td>{{detalle.notas}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a href="{% url 'ordenes:ordenes_list' %}" class="btn btn-secondary">Regresar</a>

{% endblock %}

templates/ordenes/ordenes_form.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Agregar Orden</h1>

<form action="{% url 'ordenes:ordenes_create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

templates/ordenes/ordenes_list.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Lista de Ordenes</h1>

<a class="btn btn-primary" href="{% url 'ordenes:ordenes_create' %}">Agregar orden</a>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Fecha</th>
            <th>Mesa</th>
            <th>Total</th>
            <th>Estatus</th>
        </tr>
    </thead>
    <tbody>
        {% for orden in ordenes %}
        <tr>
            <td>
                <a class="btn btn-primary" href="{% url 'ordenes:ordenes_detalle_list' orden.pk %}">Editar</a>
                <a class="btn btn-success" href="{% url 'ordenes:ordenes_pagar' orden.pk %}">Pagar</a>
            </td>
            <td>{{orden.fecha_hora}}</td>
            <td>{{orden.mesa.nombre}}</td>
            <td>{{orden.total}}</td>
            <td>{{orden.estatus}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/ordenes/ordenes_pagar.html
{% extends 'main/base_user.html' %}

{% block content %}
<h1>Pagar Orden No. {{ orden.id }} - {{ orden.fecha_hora }}</h1>

<table class="table">
    <thead>
        <tr>
            <th>Platillo</th>
            <th>Cantidad</th>
            <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for detalle in detalles %}
        <tr>            
            <td>{{detalle.platillo.nombre}}</td>
            <td>{{detalle.cantidad}}</td> 
            <td>{{detalle.subtotal}}</td>           
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2>Total: {{total}}</h2>

<form action="{% url 'ordenes:ordenes_pagar' orden.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Pagar</button>
    <a href="{% url 'ordenes:ordenes_list' %}" class="btn btn-secondary">Regresar</a>
</form>

{% endblock %}